# Generated by Django 4.0.5 on 2022-07-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Post',
            new_name='content',
        ),
    ]
